[package]
name = "limg"
version = "0.1.0"
edition = "2024"

[features]
default = ["std"]
alloc = []
std = ["alloc"]

[dependencies]
limg-core = { git = "https://github.com/limg-projects/limg-core-rs", tag = "v0.1.1" }